version: "3.7"
services:
        redis-master:
                # container_name: redis
                image: redis:5.0.5
                ports:
                        - 127.0.0.1:6379:6379
                volumes:
                        - ./tmp:/data
                        - ./redis.conf:/usr/local/etc/redis/redis.conf
                networks:
                - redis-network
        redis-slave:
                command: "redis-server --slaveof redis-master 6379"
                image: redis:5.0.5
                ports:
                        - 127.0.0.1:6380:6379
                volumes:
                        - ./redis.conf:/usr/local/etc/redis/redis.conf
                networks:
                - redis-network

networks:
        redis-network:
                driver: bridge

