version: "3.7"
services:
        redis:
                container_name: redis
                image: redis:5.0.5
                ports:
                        - 127.0.0.1:6379:6379
                volumes:
                        - ./tmp:/data
