version: '3.8'
services:
        redis:
                image: redis/redis-stack:7.0.6-RC3
                ports:
                        - 127.0.0.1:6379:6379
                        - 127.0.0.1:8001:8001
